### PR TITLE
Adds a new siteinfo package

### PR DESCRIPTION
**Pull request by nkinkade**
This new siteinfo package will be used by the maintenancestate package
to determine how many machines a site has when a site is being put into
maintenance and GMX needs to put all of the sites machines into
maintenance without also putting nonexistent ones into maintenance too.

Also, updates Go modules, and Go to v1.17 in build environments.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40)* status: 0 of 1 LGTMs obtained

___
*[`siteinfo/siteinfo.go` line 38 at r1](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N5kF4g183HpY1d0nFPq:-N5kF4g183HpY1d0nFPr:b-muo18k) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/62adabe3194a45721185495b9399823b09d035de/siteinfo/siteinfo.go#L38)):*
> ```Go
> // to be run periodically in some sort of loop. The "url" parameter is the URL
> // where the siteinfo JSON document can be downloaded.
> func (s *SiteinfoClient) Reload(ctx context.Context, url *url.URL) error {
> ```

Is the `url` parameter used?
___
*[`siteinfo/siteinfo_test.go` line 1 at r1](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N5kGGv49K4BVfuLrhCJ:-N5kGGv49K4BVfuLrhCK:b-7ecq6e) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/62adabe3194a45721185495b9399823b09d035de/siteinfo/siteinfo_test.go#L1)):*
> ```Go
> package siteinfo
> ```

Is it possible to test `Reload`, too?

**Review by nkinkade — COMMENTED** [review]
Thanks for the review, @cristinaleonr!

> *[Reviewable](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-:-N5kOcrF31J2sbQkIqxA:bi7ri10)* status: 0 of 1 LGTMs obtained

___
*[`siteinfo/siteinfo.go` line 38 at r1](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N5kF4g183HpY1d0nFPq:-N5kO6rP0h9QfGe893CI:bwgc97v) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/62adabe3194a45721185495b9399823b09d035de/siteinfo/siteinfo.go#L38)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Is the `url` parameter used?
</blockquote></details>

True. It isn't used. It was used originally, until I switched to the go/siteinfo package. I removed it. Thanks for catching that.
___
*[`siteinfo/siteinfo_test.go` line 1 at r1](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N5kGGv49K4BVfuLrhCJ:-N5kOJRsAxVPjzmY4LX5:bzb8i48) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/62adabe3194a45721185495b9399823b09d035de/siteinfo/siteinfo_test.go#L1)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Is it possible to test `Reload`, too?
</blockquote></details>

I looked at how to test `Reload()`, but it seemed to me that any test of function would essentially be a unit test of the `go/siteinfo` package, since all the function does is call that package and stuff the return value into a local variable. 

Do you have any ideas about how I could meaningfully implement testing of `Reload()`?

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40)* status: 0 of 1 LGTMs obtained

___
*[`siteinfo/siteinfo.go` line 38 at r1](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N5kF4g183HpY1d0nFPq:-N5kQzgHCR9gTXN8eIag:b-2duule) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/62adabe3194a45721185495b9399823b09d035de/siteinfo/siteinfo.go#L38)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

True. It isn't used. It was used originally, until I switched to the go/siteinfo package. I removed it. Thanks for catching that.
</blockquote></details>

Thanks! Can you also fix the comment right above, please?
___
*[`siteinfo/siteinfo_test.go` line 1 at r1](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N5kGGv49K4BVfuLrhCJ:-N5kQiEoCUjanISS7hHe:b-twewkd) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/62adabe3194a45721185495b9399823b09d035de/siteinfo/siteinfo_test.go#L1)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I looked at how to test `Reload()`, but it seemed to me that any test of function would essentially be a unit test of the `go/siteinfo` package, since all the function does is call that package and stuff the return value into a local variable. 

Do you have any ideas about how I could meaningfully implement testing of `Reload()`?
</blockquote></details>

Would it make sense for the `client` to either be passed in as an argument to the method or to be a field in the `SiteinfoClient` struct? If so, you could define a fake implementation of `client.SiteMachines()` (which you could use to test an expected return value for `Reload`).

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40)* status: 0 of 1 LGTMs obtained

___
*[`siteinfo/siteinfo.go` line 38 at r1](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N5kF4g183HpY1d0nFPq:-N5laPlW613YBH-iTkqx:b-896fja) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/62adabe3194a45721185495b9399823b09d035de/siteinfo/siteinfo.go#L38)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Thanks! Can you also fix the comment right above, please?
</blockquote></details>

Done!
___
*[`siteinfo/siteinfo_test.go` line 1 at r1](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N5kGGv49K4BVfuLrhCJ:-N5laTMi4cZKdn7zRAUF:bdl4vsh) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/62adabe3194a45721185495b9399823b09d035de/siteinfo/siteinfo_test.go#L1)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Would it make sense for the `client` to either be passed in as an argument to the method or to be a field in the `SiteinfoClient` struct? If so, you could define a fake implementation of `client.SiteMachines()` (which you could use to test an expected return value for `Reload`).
</blockquote></details>

Okay, you badgered me enough to try to add unit testing for `Reload()`. I took the route of adding a field to the `SiteinfoClient` struct to contain a `siteinfo.Client`. PTAL?

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40)* status: 0 of 1 LGTMs obtained

___
*[`siteinfo/siteinfo_test.go` line 33 at r3](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N5rRBuw35uqDvW0l7w9:-N6Ja6gL4FvfoUpzM3q2:bh55gne) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/7ebf0090be72022268eef930b3da7c468e3c5200/siteinfo/siteinfo_test.go#L33)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

I wonder if it would make sense to expose these in siteinfo.
</blockquote></details>

Good idea. I have submitted a separate PR to you to implement that in go/siteinfo: https://github.com/m-lab/go/pull/147
___
*[`siteinfo/siteinfo_test.go` line 99 at r3](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N5rR3DTBBtQbfxfCv2r:-N6JYqrh7u76dd1NJXuO:b-535nn9) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/7ebf0090be72022268eef930b3da7c468e3c5200/siteinfo/siteinfo_test.go#L99)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

In the interest of **unit** testing, this one could probably be its own test.
</blockquote></details>

I moved the error case to it's own test/function as `TestReloadWithError()`.

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40)* status: 0 of 1 LGTMs obtained

___
*[`siteinfo/siteinfo_test.go` line 33 at r3](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N5rRBuw35uqDvW0l7w9:-N6K2gSv0j3lJlh7_iXl:b-mcszip) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/7ebf0090be72022268eef930b3da7c468e3c5200/siteinfo/siteinfo_test.go#L33)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Good idea. I have submitted a separate PR to you to implement that in go/siteinfo: https://github.com/m-lab/go/pull/147
</blockquote></details>

I merged that PR, only to discover that names in "*_test.go" files are not exported by a package. I somehow don't like the idea of putting all those mock structs in the main package file. Maybe just defining them again in my test file is easiest/best here?

**Review by nkinkade — COMMENTED** [review]
@stephen-soltesz: @cristinaleonr is out for the rest of the week. Might you be able to look over this PR? I've already implemented a number of good suggestions and observations from @cristinaleonr.

> *[Reviewable](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-:-N6K37xx41pYK4NL7tfz:b-g3895z)* status: 0 of 1 LGTMs obtained

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
Of general interest based on earlier questions a few weeks ago: https://github.com/uber-go/guide/blob/master/style.md#pointers-to-interfaces

> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-:-N6L6u2h2FKu-z997h7Z:buhhc9e)* status: 0 of 1 LGTMs obtained

___
*[`.travis.yml` line 4 at r4](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N6L2VVU--X6nviVcdmq:-N6L2VVV9HGSF8u8Nw5x:bh1vkn9) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/f537b564722e468c56349dd250f2a96f01d6082e/.travis.yml#L4)):*
> ```YAML
> 
> go:
> - 1.17
> ```

No wrong answer: why not 1.18?
___
*[`siteinfo/siteinfo.go` line 13 at r4](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N6L5KHq68jO3IkOHeV8:-N6L5KHq68jO3IkOHeV9:b-hdr9yq) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/f537b564722e468c56349dd250f2a96f01d6082e/siteinfo/siteinfo.go#L13)):*
> ```Go
> 
> // Siteinfo defines a new siteinfo interface for interacting with the siteinfo API.
> type Siteinfo interface {
> ```

Do not separate interface declaration and use. Alternately: declare interfaces in the packages where they are first used. This is another thing that you can find examples of this in some of our other code, but that's before we knew better.

See: https://github.com/golang/go/wiki/CodeReviewComments#interfaces
___
*[`siteinfo/siteinfo.go` line 19 at r4](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N6L4kvS7TAKWlgB29GC:-N6L4kvT9_6KuTZHfqZX:b3r5q6q) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/f537b564722e468c56349dd250f2a96f01d6082e/siteinfo/siteinfo.go#L19)):*
> ```Go
> 
> // SiteinfoClient implements the Siteinfo interface.
> type SiteinfoClient struct {
> ```

Avoid package-type repetition. https://go.dev/doc/effective_go#names

In this case, `siteinfo.Client` could be just right.
___
*[`siteinfo/siteinfo.go` line 27 at r4](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N6L4wKH2-2HllcOmvXq:-N6L4wKH2-2HllcOmvXr:b-4rkuhj) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/f537b564722e468c56349dd250f2a96f01d6082e/siteinfo/siteinfo.go#L27)):*
> ```Go
> // SiteMachines takes a short site name parameter (e.g. abc02), and will return
> // the machines (e.g., mlab1, mlab2) that the site contains.
> func (s *SiteinfoClient) SiteMachines(site string) ([]string, error) {
> ```

Again shorter may be clearer. When the calling code is using a Client, the parameter will convey that this is filtered by sites. e.g. `c.Machines(site)` `Site` is not needed in the method name.
___
*[`siteinfo/siteinfo_test.go` line 33 at r3](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N5rRBuw35uqDvW0l7w9:-N6L97E89t25EvxlU5nl:b-citd5k) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/7ebf0090be72022268eef930b3da7c468e3c5200/siteinfo/siteinfo_test.go#L33)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I merged that PR, only to discover that names in "*_test.go" files are not exported by a package. I somehow don't like the idea of putting all those mock structs in the main package file. Maybe just defining them again in my test file is easiest/best here?
</blockquote></details>

For types that are generally useful for testing, I recommend creating a `<foo>test` package within the primary package directory. This is borrowing from the pattern in the standard library for packages like `http/httptest`. So for the m-lab/go/provider package, create a subdirectory `m-lab/go/provider/providertest` that includes the helpful fake implementations and reference them in the provider tests and here.

Aside: @saiedkazemi - trust your instincts.

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40)* status: 0 of 1 LGTMs obtained

___
*[`siteinfo/siteinfo.go` line 13 at r4](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N6L5KHq68jO3IkOHeV8:-N6Q9Nl28xCEN-zn_p-Y:b-x4h81r) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/f537b564722e468c56349dd250f2a96f01d6082e/siteinfo/siteinfo.go#L13)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I have moved the `Siteinfo` interface definition to maintenancestate/state.go. This package now has a struct named `Siteinfo` which implements the `maintenancestate.Siteinfo` interface. Is it a problem that the struct is named the same thing as the interface it implements? They are in different packages, and it seems to work. I couldn't think of a better name for the struct. Anything with "reloader" in it didn't seem like enough, since the package also has a function `Machines()` which returns the machines associated with a given site, so "realoder" didn't seem descriptive enough.
</blockquote></details>

I would recommend a general pattern where the interface (even if just logical / not explicitly defined anywhere) is a short name, and specific implementations to include additional meaningful attributes. For example:

* Writer interface with  BufferedWriter, and/or NullWriter, and/or FlushingWriter, StderrWriter, etc. for implementations.

The interface name is often a "thing-er", like Writer, or Closer, or Handler, etc... The concrete implementation is a kind of thing-er, like the examples above, where the name gives a reader a hint about what makes it distinct. 

The interface for the type here has two principle methods: `Machines` (which finds machines for a site), and `Reload` (for updating the sites-to-machines map). This is me riffing on some ideas for naming here, please mix and match:

* sites.Loader
* sites.MachinesLoader
* sites.CachingClient
* sites.MachinesReloader
* siteinfo.CachingLoader
* siteinfo.Wrapper
* siteinfo.CachingWrapper
___
*[`siteinfo/siteinfo.go` line 19 at r4](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N6L4kvS7TAKWlgB29GC:-N6Q6KiT4KW1M8iNhfD0:b-bstasc) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/f537b564722e468c56349dd250f2a96f01d6082e/siteinfo/siteinfo.go#L19)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Fixed, I believe.
</blockquote></details>

Hmm, the type would be referenced as `siteinfo.Siteinfo` now... This would be a common pattern in Python, but discouraged in Go.
___
*[`siteinfo/siteinfo_test.go` line 87 at r5](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N6Q5lwy6EKeHfOuzoNu:-N6Q5lwy6EKeHfOuzoNv:blfc74w) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/4e6e3b68768e6c6aa37dd787169f49e7cc2f75bd/siteinfo/siteinfo_test.go#L87)):*
> ```Go
> }
> 
> func TestSiteMachines(t *testing.T) {
> ```

nit: please update test name to reflect method under test. (I forget this all the time, which is why I know to look for it)

**Review by nkinkade — COMMENTED** [review]
@stephen-soltesz: Thank you for the suggestions. PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-:-N6TfCQxA9hPHYTKqVeB:bkbf3lj)* status: 0 of 1 LGTMs obtained

___
*[`siteinfo/siteinfo.go` line 13 at r4](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N6L5KHq68jO3IkOHeV8:-N6TeFrNDYVM_JNu-M3w:b-u0d0eh) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/f537b564722e468c56349dd250f2a96f01d6082e/siteinfo/siteinfo.go#L13)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I would recommend a general pattern where the interface (even if just logical / not explicitly defined anywhere) is a short name, and specific implementations to include additional meaningful attributes. For example:

* Writer interface with  BufferedWriter, and/or NullWriter, and/or FlushingWriter, StderrWriter, etc. for implementations.

The interface name is often a "thing-er", like Writer, or Closer, or Handler, etc... The concrete implementation is a kind of thing-er, like the examples above, where the name gives a reader a hint about what makes it distinct. 

The interface for the type here has two principle methods: `Machines` (which finds machines for a site), and `Reload` (for updating the sites-to-machines map). This is me riffing on some ideas for naming here, please mix and match:

* sites.Loader
* sites.MachinesLoader
* sites.CachingClient
* sites.MachinesReloader
* siteinfo.CachingLoader
* siteinfo.Wrapper
* siteinfo.CachingWrapper
</blockquote></details>

Thank you for the ideas. Naming is hard. From your ideas I liked `sites.CachingClient`. I renamed the package from "siteinfo" to just "sites", and the main struct of the package is now named `CachingClient`. Renaming the package helps to resolve the awkward name collision with m-lab/go/siteinfo.
___
*[`siteinfo/siteinfo.go` line 19 at r4](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N6L4kvS7TAKWlgB29GC:-N6Tf6XF7theCyXlo100:bq53lae) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/f537b564722e468c56349dd250f2a96f01d6082e/siteinfo/siteinfo.go#L19)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Hmm, the type would be referenced as `siteinfo.Siteinfo` now... This would be a common pattern in Python, but discouraged in Go.
</blockquote></details>

It is now `sites.CachingClient`.
___
*[`siteinfo/siteinfo_test.go` line 87 at r5](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N6Q5lwy6EKeHfOuzoNu:-N6Tf20SChyehjaKzU-r:bt2vr1b) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/4e6e3b68768e6c6aa37dd787169f49e7cc2f75bd/siteinfo/siteinfo_test.go#L87)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: please update test name to reflect method under test. (I forget this all the time, which is why I know to look for it)
</blockquote></details>

Fixed.

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
:lgtm: with the last suggestion for guarding update/access to the cached `Sites` field.

> *[Reviewable](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-:-N6Tk2-ABDhK67Xb2K8f:b-i6smkg)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[`siteinfo/siteinfo.go` line 13 at r4](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N6L5KHq68jO3IkOHeV8:-N6TiwDjDgXIo8j9GXPZ:b-8fx2u7) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/f537b564722e468c56349dd250f2a96f01d6082e/siteinfo/siteinfo.go#L13)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Thank you for the ideas. Naming is hard. From your ideas I liked `sites.CachingClient`. I renamed the package from "siteinfo" to just "sites", and the main struct of the package is now named `CachingClient`. Renaming the package helps to resolve the awkward name collision with m-lab/go/siteinfo.
</blockquote></details>

:+1: 
___
*[`sites/sites.go` line 36 at r6](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N6TjX337hmXQ4zEoVj2:-N6TjX337hmXQ4zEoVj3:btx0lyd) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/08b97da9bffc9f3355d68d4b07896b23e094bd0a/sites/sites.go#L36)):*
> ```Go
> 		return err
> 	}
> 	cc.Sites = siteMachines
> ```

This is not thread safe. Since Machines and Reload are called asynchronously, I think this and the access above should be guarded by `sync.Mutex` lock. (if the calls were guaranteed to be synchronous, then it could be sufficient to document this limitation and leave the caller to guarantee safe access).

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[`sites/sites.go` line 36 at r6](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N6TjX337hmXQ4zEoVj2:-N6Tp1yiEEaep62cDYGO:b-b8off3) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/08b97da9bffc9f3355d68d4b07896b23e094bd0a/sites/sites.go#L36)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This is not thread safe. Since Machines and Reload are called asynchronously, I think this and the access above should be guarded by `sync.Mutex` lock. (if the calls were guaranteed to be synchronous, then it could be sufficient to document this limitation and leave the caller to guarantee safe access).
</blockquote></details>

Is it not okay if `Machines()` and `Reload()` are called simultaneously by two different Go routines? Only `Reload()` modifies anything, and it should only ever be called in a serial fashion through the `memoryless` package, right? I'm just trying to be sure I understand how things are unsafe here before I go adding code that I don't fully understand.

If I put a lock on `Reload()`, then `Machines()` can still be called by multiple Go routines, correct?

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[`sites/sites.go` line 36 at r6](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N6TjX337hmXQ4zEoVj2:-N6TwS8xD2Nao7VgLsDb:byp5v07) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/08b97da9bffc9f3355d68d4b07896b23e094bd0a/sites/sites.go#L36)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Is it not okay if `Machines()` and `Reload()` are called simultaneously by two different Go routines? Only `Reload()` modifies anything, and it should only ever be called in a serial fashion through the `memoryless` package, right? I'm just trying to be sure I understand how things are unsafe here before I go adding code that I don't fully understand.

If I put a lock on `Reload()`, then `Machines()` can still be called by multiple Go routines, correct?
</blockquote></details>

It is technically not safe because one thread/goroutine may try to read from cc.Sites at the same time another thread/goroutine is trying to overwrite it. Go does not provide guarantees about atomic assignments, so weird things could happen (with low probability, but still technically unsafely).

Same idea as here: https://github.com/m-lab/github-maintenance-exporter/blob/fec34010e211ba3491d77e4919d03c3586900ed8/handler/handler.go#L80-L83

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[`sites/sites.go` line 36 at r6](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N6TjX337hmXQ4zEoVj2:-N6UZdb1EJtU8kT_3VBt:b-qp49nl) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/08b97da9bffc9f3355d68d4b07896b23e094bd0a/sites/sites.go#L36)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

It is technically not safe because one thread/goroutine may try to read from cc.Sites at the same time another thread/goroutine is trying to overwrite it. Go does not provide guarantees about atomic assignments, so weird things could happen (with low probability, but still technically unsafely).

Same idea as here: https://github.com/m-lab/github-maintenance-exporter/blob/fec34010e211ba3491d77e4919d03c3586900ed8/handler/handler.go#L80-L83
</blockquote></details>

@stephen-soltesz: I have added mutex locks to both `CachingClient` methods. PTAL?

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-:-N6Ua7kI-8TZIBtrDaow:bnfp4nl)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[`sites/sites.go` line 15 at r7](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N6Ua1Yl1IU_JXLL41Wf:-N6Ua1Yl1IU_JXLL41Wg:b-d1n9rm) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/47a4ef965fa05d885cd43e4321375537cee4dc87/sites/sites.go#L15)):*
> ```Go
> // CachingClient implements the maintenancestate.Sites interface.
> type CachingClient struct {
> 	mu       sync.Mutex
> ```

nit: I recommend placing the private fields last.

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[`sites/sites.go` line 15 at r7](https://reviewable.io/reviews/m-lab/github-maintenance-exporter/40#-N6Ua1Yl1IU_JXLL41Wf:-N6Uantq-gm1uYf2JLUE:b-3q0ugo) ([raw file](https://github.com/m-lab/github-maintenance-exporter/blob/47a4ef965fa05d885cd43e4321375537cee4dc87/sites/sites.go#L15)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: I recommend placing the private fields last.
</blockquote></details>

I reordered the fields with exported fields sorted alphabetically and the single unexported field last.

**Pull request merged**
